############
############
############


#A Preload Functions

def evaluate_error_rate(messages):
    """
    Purpose: Evaluate the error rate of any agent over time.

    Args:
    messages (list): List of messages generated by agent and extended with each new request t+1.

    Returns:
    float: Ratio of Errors to Total Messages.
    """
    error_count = sum(1 for msg in messages if "error" in msg.lower())
    total_messages = len(messages)
    error_rate = error_count / total_messages if total_messages > 0 else 0
    return error_rate


def count_steps_proposed(api_response_text):
    """
    Purpose: Counts the number of bullet points in the given text.
    Then passed as an argument into function "evaluate_environment_complexity".
    
    Args:
    LLM text output. Currently works for OpenAI API only.

    Returns:
    int: Number of bullet points
    """
    # Define possible bullet point markers
    bullet_markers = ['-', '*', '•']
    
    # Split the text into lines
    lines = api_response_text.split('\n')
    
    # Count the number of lines that start with a bullet marker
    bullet_count = sum(1 for line in lines if line.strip().startswith(tuple(bullet_markers)))
    
    return bullet_count

#CONSENSUS

def calculate_consensus_score(responses):
    """
    Purpose: Calculate the rate of consensus between n models, by triangulating a similarity score.

    Args: Vector of responses from n models.

    Returns:
    float: consensus score
    """
    # Encode responses to get their embeddings
    embeddings = model.encode(responses, convert_to_tensor=True)
    
    # Calculate cosine similarities between each pair of responses
    similarities = util.pytorch_cos_sim(embeddings, embeddings)
    
    # Calculate the mean of the upper triangular matrix of similarities
    num_responses = len(responses)
    upper_triangle_indices = np.triu_indices(num_responses, k=1)
    consensus_score = similarities[upper_triangle_indices].mean().item()
    
    return consensus_score

def calculate_ag_rationality(problem_type):
    """
    Purpose: Calculate rationality fitness of an agent based on the problem type. Is passed as an argument into function evaluate_fitness.
    """
    if problem_type == "deterministic":
        ag_rationality = (accuracy_score * 1.5 + reasoning_score * 1.5 + future_score * 1.2 + coding_score + math_score) / 5
    elif problem_type == "predictive":
        ag_rationality = (accuracy_score * 1.2 + reasoning_score + future_score + coding_score * 1.5 + math_score * 1.5) / 5
    elif problem_type == "code_based":
        ag_rationality = (accuracy_score * 1.2 + reasoning_score * 1.5 + future_score + coding_score * 2 + math_score) / 5
    elif problem_type == "philosophical":
        ag_rationality = (accuracy_score * 1.2 + reasoning_score * 1.5 + future_score * 1.5 + coding_score + math_score) / 5
    else:
        raise ValueError("Invalid problem_type provided")

    return ag_rationality


############
############
############


#Benchmark Functions

#RATIONALITY

def evaluate_fitness(model_type, agent_type, problem_type):
    """
    Future: a parameter "weights" could be added that allows the Observer Instance to slect its own weights for problem solving
    """
    model_type_label = {"gpt-3.5": 1, "gpt-4": 2, "gpt-4o": 2, "gemini": 3, "gemini-ultra": 4, "mistral": 5}[model_type]
    agent_type_label = {"LLM": 1, "bot": 2}[agent_type]
    accuracy_score = {"gpt-3.5": 0, "gpt-4": 0, "gpt-4o": 0, "gemini": 0, "gemini-ultra": 0, "mistral": 0}[model_type] #MMLU scores on accuracy
    reasoning_score = {"gpt-3.5": 0, "gpt-4": 0, "gpt-4o": 0, "gemini": 0, "gemini-ultra": 0, "mistral": 0}[model_type] #HellaSwag scores on reasoning
    future_score = {"gpt-3.5": 0, "gpt-4": 0, "gpt-4o": 0, "gemini": 0, "gemini-ultra": 0, "mistral": 0}[model_type] #BBHard score on expected future capabilities
    coding_score = {"gpt-3.5": 0, "gpt-4": 0, "gpt-4o": 0, "gemini": 0, "gemini-ultra": 0, "mistral": 0}[model_type] #HumanEval scores on coding
    math_score = {"gpt-3.5": 0, "gpt-4": 0, "gpt-4o": 0, "gemini": 0, "gemini-ultra": 0, "mistral": 0}[model_type] #MATH score on Mathematical reasoning
    ag_rationality = calculate_ag_rationality(problem_type)
    return ag_rationality, model_type_label, agent_type_label


#ACT MAX SCORE
def calculate_act_max_score(ag_rationality, consensus_score, weight_adaptationy=0.4, weight_consensus=0.3, weight_benchmark=0.3):
    act_max_score = (weight_consensus * consensus_score) + (weight_benchmark * ag_rationality) + # (weight_adaptationy * adaptation_rate) -> define adaptation function
    return act_max_score


#ADAPTATION RATE
def evaluate_adaptive_behavior(vector_t, vector_t1): #function is a draft not yet complete / functional
    """
    Evaluates the adaptive behavior by comparing changes in model type between time steps t and t+1.
    """
    act_max_score_t, model_type_t, time_t = vector_t
    act_max_score_t1, model_type_t1, time_t1 = vector_t1
    
    if model_type_t != model_type_t1:
        adaptation_rate =+ 1
    
    return adaptation_rate

#ENVIRONMENT COMPLEXITY
def evaluate_environment_complexity(problem_scope, problem_type, time, num_agents, response):
    """
    Purpose: Calculates the complexity of the environment at timestep t.

    Considers the following factors: observability of the problem from the agent's pov, nature of the problem from the agents pov,
    time that has passed since beginning of request, number of active agents in env, number of steps proposed by agent with highest planning benchmark,
    predicted number of steps left (add extra loop for new actions in case of negative values in the future).

    Args: Manual description of problem completeness - fixed value (env_obs), Manual description of problem's nature - fixed value (env_nat), time, number n of active agents (num_agents), response of agent with highest act_max_score (response).

    """
    problem_scope_label = {"open": 1, "closed": 0}[problem_scope] ## observability (complete / partial): complete if closed problem, partial if open problem
    problem_type_label = {"deterministic": [1,0,0,0], "predictive": [0,1,0,0], "code_based": [0,0,1,0], "philosophical": [0,0,0,1]}[problem_type] # environment effect (deterministic / predictive):
    time += 1   # timesteps that have passed (ordinal) <p>
    num_agents = num_agents # number of agents (n) <p>
    num_steps_proposed = count_steps_proposed(response) # ability to plan <p>
    ratio_steps_left = (num_steps_proposed - time) / num_steps_proposed 
    return problem_scope_label, problem_type_label, time, num_agents, num_steps_proposed, ratio_steps_left


############
############
############


#GENERATE FEATURE VECTOR FUNCTIONS

#Implement Feature Vector
def generate_feature_vector(act_max_score, model_type, agent_type, problem_scope_label, problem_type_label, time, num_agents, response, adaptation_rate=0):
    # Extract features from each function
    act_max_score = act_max_score
    rationality_features = evaluate_fitness(model_type, agent_type, problem_type)
    adaptation_rate = adaptation_rate
    env_features = evaluate_environment_complexity(env_obs, env_nat, time, num_agents, response)
    error_rate = evaluate_error_rate(messages)
    
    # Aggregate all features into a single vector
    feature_vector = [act_max_score] + list[rationality_features] + [adaptation_rate] + list(env_features) + [error_rate]
    
    return feature_vector
